// 1
// var now = new Date();
// console.log(now.getUTCDate());

// // 2
// var now = new Date("january 2 2005");
// console.log(now.getFullYear());

// 3
// var now = new Date();
// console.log(now.getHours());
// console.log(now.getSeconds());
// console.log(now.getMilliseconds());

// 4
// var now = new Date("january 2 2005");
// console.log(now.getHours());
// console.log(now.getSeconds());
// console.log(now.getMilliseconds());

// 5
// var now = new Date();
// now.setDate(20);
// now.setFullYear(2020);
// console.log(now.setFullYear(2020));

// // 6
// var now = new Date("january 2 2005");
// console.log(now.setDate(20));
// now.setDate(5);
// now.setMinutes(20)
// console.log(now.getMinutes());


// const date  = new Date();
// let sDate = date.setDate(2);
// console.log(sDate); // ==> 0 to

// date.setDate(2);
// console.log(date.toString()); // ==> 0 to


// 7
// var newdate  = new Date();
// console.warn(newdate.getFullYear());

// var newdate  = new Date();
// console.warn(newdate.getDate());

// 8
// let d = new Date();
// console.log(d.toLocaleTimeString());

// 9
// let d = new Date();
// console.log(d.toLocaleDateString());

// 10
// let d = new Date();
// console.log(d.toTimeString());

// 11
// let d = new Date();
// d.toTimeString();

// 12
// let d = new Date();
// d.toDateString();

// 13
// let d = new Date();
// d.setTime(1627924800000);

// 14
// let d = new Date();
// d.setMilliseconds(999);

// 15
// let d = new Date();
// d.setMilliseconds(999);

// // 16
// let d = new Date();
// d.setSeconds(30);

// 17
// let d = new Date();
// d.setMinutes(45);

// 18
// let d = new Date();
// d.setHours(17);

// // 19
// let d = new Date();
// d.setMonth(5);

// // 20
// let d = new Date();
// d.setDate(20);

// // 21
// const d = new Date();
// d.getTime();

    // // 22
    // const d = new Date();
    // d.getMilliseconds();

// // 23
// const d = new Date();
// d.getMilliseconds();

// // 24
// const d = new Date();
// d.getSeconds();

// // 25
// const d = new Date();
// d.getMinutes();


// // 26
// const d = new Date();
// d.getHours();

// 27
// const d = new Date();
// d.getDate();

// 28
// const d = new Date();
// d.getMonth();

// // 29
// const d = new Date();
// d.getFullYear();

// console.log(10*2/5+Math.pow(2,3)-4%3);