// 1
// var now = new Date();
// console.log(now.getUTCDate());

// // 2
// var now = new Date("january 2 2005");
// console.log(now.getFullYear());

// 3
// var now = new Date();
// console.log(now.getHours());
// console.log(now.getSeconds());
// console.log(now.getMilliseconds());

// 4
// var now = new Date("january 2 2005");
// console.log(now.getHours());
// console.log(now.getSeconds());
// console.log(now.getMilliseconds());

// 5
// var now = new Date();
// now.setDate(20);
// now.setFullYear(2020);
// console.log(now.setFullYear(2020));

// // 6
// var now = new Date("january 2 2005");
// console.log(now.setDate(20));
// now.setDate(5);
// now.setMinutes(20)
// console.log(now.getMinutes());


// const date  = new Date();
// let sDate = date.setDate(2);
// console.log(sDate); // ==> 0 to

// date.setDate(2);
// console.log(date.toString()); // ==> 0 to


// 7
// var newdate  = new Date();
// console.warn(newdate.getFullYear());

// var newdate  = new Date();
// console.warn(newdate.getDate());

